### ISSUE TITLE
Bundle mode

### ISSUE THREAD

**Issue by geelen** [geelen/jspm-loader-css#1]
Need to figure out a way to have this work in bundle mode.

**Comment by geelen** [comment]
Working on this on the build-mode branch, got stuck straight away. First thing I tried was to [short-circuit the fetch](https://github.com/geelen/jspm-loader-css/commit/b3f96002847869bd67180dc08343dccb0caf0275) like I did in plugin-postcss, but this is what I get:

``` sh
     Building the bundle tree for src/main...

       src/main
       src/main.css!npm:jspm-loader-css@0.0.5


err  TypeError: Cannot read property 'suppressDeprecationMessages' of undefined
         at Logger.deprecate (file:/Users/glen/src/projects/css-modules/jspm-demo/jspm_packages/npm/babel-core@5.5.4/browser.js:8889:24)
         at File.normalizeOptions (file:/Users/glen/src/projects/css-modules/jspm-demo/jspm_packages/npm/babel-core@5.5.4/browser.js:8271:18)
         at new File (file:/Users/glen/src/projects/css-modules/jspm-demo/jspm_packages/npm/babel-core@5.5.4/browser.js:8237:22)
         at TransformerPipeline.transform (file:/Users/glen/src/projects/css-modules/jspm-demo/jspm_packages/npm/babel-core@5.5.4/browser.js:12107:16)
         at /usr/local/lib/node_modules/jspm/node_modules/systemjs-builder/compilers/es6.js:125:31
         at tryCatchReject (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at Pending.run (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)
         at Scheduler._drain (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
```

Any thoughts, @guybedford? Is it because my loader file itself is written in ES6 or something?

**Comment by guybedford** [comment]
This was a Babel bug I believe, if you update Babel it should be working now.

**Comment by guybedford** [comment]
Also is it clear what the bundle hook does in https://github.com/systemjs/plugin-css/blob/master/css.js#L78? Just let me know.

**Comment by geelen** [comment]
Right, so here's the crucial point: https://github.com/geelen/jspm-loader-css/blob/2bc54a7c9e7aa7c6f039b11582e5b1b26427b1b9/index.js#L51

That's called when a CSS file references another (for now, just a CSS Modules `:import` statement but the same would be used in an `@import`, I think). So when I run this in the browser, you see all the "Importing" statements printed, then as they all get resolved, the results are all passed back:

![image](https://cloud.githubusercontent.com/assets/23264/8051977/e75f9784-0ec5-11e5-8ff8-85972e139d73.png)

Running that in build mode, here's the output:

![image](https://cloud.githubusercontent.com/assets/23264/8051988/06fe8348-0ec6-11e5-8057-a61c812a5362.png)

So things are happening in the right order, but the exports aren't being passed through. I can sorta see how this is what you'd expect in JS-land, you don't actually want to execute each file. But here, I guess I do?

**Comment by geelen** [comment]
Right, well I figured out a way. It may not be the best way, but it works! https://github.com/geelen/jspm-loader-css/pull/4

**Comment by f15gdsy** [comment]
Hi, is bundle mode ready?
I'm using v0.1.6 and use 'jspm bundle-sfx'. The styles are not present in the output, though the prefixed classes are set correctly for html tags.
